/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseDesktop: typeof import('./src/components/BaseDesktop/BaseDesktop.vue')['default']
    DragItem: typeof import('./src/components/dragdrop/DragItem.vue')['default']
    DropContent: typeof import('./src/components/dragdrop/DropContent.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GroundGlass: typeof import('./src/components/GroundGlass/GroundGlass.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MoveMask: typeof import('./src/components/dragdrop/MoveMask.vue')['default']
    PreviewItem: typeof import('./src/components/dragdrop/PreviewItem.vue')['default']
    PreviewLayout: typeof import('./src/components/dragdrop/PreviewLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideDrawer: typeof import('./src/components/Drawer/SideDrawer.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
    WqTab: typeof import('./src/components/WqTab/WqTab.vue')['default']
    WqTitle: typeof import('./src/components/WqTitle/WqTitle.vue')['default']
    WqUpload: typeof import('./src/components/uploadComp/wqUpload.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
