import { CompApp } from '@/type/compApp';

export const demoTestList: CompApp[] = [
	{
		column: 5,
		row: 5,
		key: 'demo-component',
		title: '这是一个简单的计算器',
		defaultDrop: { key: 'demo-component', title: '1x1', column: 1, row: 1 },
		url: 'http://127.0.0.1:8000/test/test.html',
		previewUrl: 'https://tse3-mm.cn.bing.net/th/id/OIP-C.aI5TikqkSMfOEXA7Nns9vwHaEz?w=277&h=180&c=7&r=0&o=5&pid=1.7',
	},
	{
		column: 1,
		row: 1,
		key: 'demo-component',
		title: 'haha',
		defaultDrop: {
			column: 1,
			row: 1,
			key: 'demo-component',
			title: 'haha',
		},
		url: 'http://127.0.0.1:8000/',
		previewUrl: 'https://tse3-mm.cn.bing.net/th/id/OIP-C.aI5TikqkSMfOEXA7Nns9vwHaEz?w=277&h=180&c=7&r=0&o=5&pid=1.7',
	},
	{
		column: 1,
		row: 1,
		key: 'demo-component',
		title: 'haha',
		defaultDrop: { key: 'demo-component', title: '1x1', column: 1, row: 1 },
		url: 'http://127.0.0.1:8000/',
		previewUrl: 'https://tse3-mm.cn.bing.net/th/id/OIP-C.aI5TikqkSMfOEXA7Nns9vwHaEz?w=277&h=180&c=7&r=0&o=5&pid=1.7',
	},
	{
		column: 1,
		row: 1,
		key: 'demo-component',
		title: 'haha',
		defaultDrop: {
			column: 1,
			row: 1,
			key: 'demo-component',
			title: 'haha',
		},
		url: 'http://127.0.0.1:8000/',
		previewUrl: 'https://tse3-mm.cn.bing.net/th/id/OIP-C.aI5TikqkSMfOEXA7Nns9vwHaEz?w=277&h=180&c=7&r=0&o=5&pid=1.7',
	},
	{
		column: 1,
		row: 1,
		key: 'demo-component',
		title: 'haha',
		defaultDrop: { key: 'demo-component', title: '1x1', column: 1, row: 1 },
		url: 'http://127.0.0.1:8000/',
		previewUrl: 'https://tse3-mm.cn.bing.net/th/id/OIP-C.aI5TikqkSMfOEXA7Nns9vwHaEz?w=277&h=180&c=7&r=0&o=5&pid=1.7',
	},
	{
		column: 3,
		row: 3,
		key: 'demo-component',
		title: 'test1',
		defaultDrop: {
			column: 1,
			row: 1,
			key: 'demo-component',
			title: 'test1',
		},
		url: 'http://127.0.0.1:8000/test/test1.html',
		previewUrl: 'https://tse3-mm.cn.bing.net/th/id/OIP-C.aI5TikqkSMfOEXA7Nns9vwHaEz?w=277&h=180&c=7&r=0&o=5&pid=1.7',
	},
];
